default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: openbudgets_development
  min_messages: notice

test:
  <<: *default
  database: openbudgets_test
  min_messages: error

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
